# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainsub.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests
import sys
from PyQt5.QtWidgets import QApplication,QMainWindow
from tkvidgui import main
import threading

class Ui_Form_sub(object):
    def start_vidcenter(self):
        try:
            true = True
            false = False
            print(self.text.text()[0:2])
            if self.text.text()[0:2] == 'BV':
                info = eval(requests.get('http://api.bilibili.com/x/web-interface/view?bvid={}'.format(self.text.text())).text)['data']
            elif self.text.text()[0:2] == 'av':
                print(2)
                info = eval(requests.get('http://api.bilibili.com/x/web-interface/view?aid={}'.format(self.text.text()[2::])).text)['data']
            elif self.text.text()[0:2] == 'ss':
                print(3)
                info=eval(requests.get('http://api.bilibili.com/pgc/view/web/season?season_id={}'.format(self.text.text()[2::])).text)
            threading.Thread(target=main,args=(info,)).start()

        except Exception as e:
            print('starterr',e)

    def setupUi(self, Form,usrlist):
        Form.setObjectName("Form")
        Form.resize(745, 338)
        self.face = QtWidgets.QLabel(Form)
        self.face.setGeometry(QtCore.QRect(20, 20, 211, 211))
        self.face.setObjectName("face")
        self.name = QtWidgets.QLabel(Form)
        self.name.setGeometry(QtCore.QRect(240, 10, 441, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.name.setObjectName("name")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(580, 150, 160, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_coin = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_coin.setObjectName("label_coin")
        self.horizontalLayout.addWidget(self.label_coin)
        self.label_coin_amount = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_coin_amount.setObjectName("label_coin_amount")
        self.horizontalLayout.addWidget(self.label_coin_amount)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(510, 100, 178, 81))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.exp = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.exp.setObjectName("exp")
        self.horizontalLayout_2.addWidget(self.exp)
        self.exp_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.exp_2.setObjectName("exp_2")
        self.horizontalLayout_2.addWidget(self.exp_2)
        self.label_vipstate = QtWidgets.QLabel(Form)
        self.label_vipstate.setGeometry(QtCore.QRect(350, 100, 101, 79))
        self.label_vipstate.setObjectName("label_vipstate")
        self.text = QtWidgets.QLineEdit(Form)
        self.text.setGeometry(QtCore.QRect(20, 210, 480, 40))
        self.text.setObjectName("text")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(505, 210, 50, 40))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 320, 251, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Form,usrlist)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form,usrlist):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "用户信息"))
        self.face.setText(_translate("Form", "头像"))
        self.name.setText(_translate("Form", usrlist['name']))
        self.label_coin.setText(_translate("Form", "硬币图片"))
        self.label_coin_amount.setText(_translate("Form", str(usrlist['coins'])))
        self.exp.setText(_translate("Form", str(usrlist['level'])+'级'))
        self.exp_2.setText(_translate("Form", str(usrlist['exp'])))
        self.label_vipstate.setText(_translate("Form", usrlist['viplabel']))
        self.text.setText('在此处粘贴av,bv,ss号或视频\番剧链接')
        self.pushButton.setText(_translate("Form", "Go"))
        self.pushButton.pressed.connect(self.start_vidcenter)
        self.label.setText(_translate("Form", "©梯子科技工作室 制作"))

        jpgcoin = QtGui.QPixmap('img\coin.jpg')
        self.label_coin.setPixmap(jpgcoin)

        jpgface=QtGui.QPixmap(r'img\face.jpg').scaled(150,150)
        self.face.setPixmap(jpgface)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    SubWindow = QMainWindow()
    ui = Ui_Form_sub()  # ui_from是类名
    name = {'mid': 235098388, 'name': '张三说冥法', 'level': 5, 'exp': '17469/28800', 'coins': 70.9, 'viptype': 2,
            'viplabel': '年度大会员'}
    ui.setupUi(SubWindow,name)
    SubWindow.show()
    sys.exit(app.exec_())
